[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild" # gives you native fetch on Node 18+ and bundling if needed
  external_node_modules = []

[[headers]]
  for = "/netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
